version: "3"
services:
  app:
    build: .
    image: test-ms-beer
    container_name: test-ms-beer-app
    ports:
      - "8080:8080"
    environment:
      MYSQL_HOST: db
      MYSQL_DATABASE: beers
      MYSQL_USER: root
      MYSQL_PASSWORD: passwd123
      CURRENCYLAYER_ACCESS_KEY: 50c385edbb018f480d65a1b0db544501
    depends_on:
      - db
    
  db:
    image: mysql
    container_name: test-ms-beer-db
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: beers
      MYSQL_ROOT_PASSWORD: passwd123
    volumes:
      - ./docker/db:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"